### PR TITLE
Fixing calendar links and beautifying it

### LINKED ISSUE #100: Events Page: Improve Calendar & Enhance CSS
Now that we have a calendar working with different views switch like day, month, year in #99.

- Introduce CSS which may improve the current messy calendar look.
- Introduce margin and full page calendar.

cc: @mrbobbytables @parispittman 

/kind feature
/priority important-soon

### PR DESCRIPTION
**Pull request by vishakhanihore**
Fixes #100 
- Fixed link open for popup.
- Changed the size of calendar.

### CODE REVIEW

**Comment by mrbobbytables** [comment]
Thanks @vishakhanihore \o/
Would you mind squashing them down? Once that's done I'll approve 👍

**Comment by vishakhanihore** [comment]
@mrbobbytables Squashed the commits

**Comment by mrbobbytables** [comment]
Thanks!
/approve

**Comment by mrbobbytables** [comment]
woops, forgot to toss an lgtm on it
/lgtm

**Pull request merged**
