### PR TITLE
[WIP-DO NOT MERGE] Refactoring bash to python

### PR DESCRIPTION
**Pull request by markyjackson-taulia**
Signed-off-by: markyjackson-taulia <marky.r.jackson@gmail.com>

[WIP-DO NOT MERGE] Refactoring bash to python for gen-content.sh
Still more work to do

### CODE REVIEW

**Comment by markyjackson-taulia** [comment]
This is for issue #93

**Comment by markyjackson-taulia** [comment]
@mrbobbytables I remember you saying something about wanting to remove a lot of the `grep` items but I wanted to be sure before I headed down that path.

Also going to ping Laura (cannot tag her) for another set of eyes

**Comment by mrbobbytables** [comment]
From [previous discussion](https://github.com/kubernetes-sigs/contributor-site/issues/93#issuecomment-620080117), going to go ahead and close this out for now -- We will revisit later.

Thanks @markyjackson-taulia ❤️ 
/close

**Pull request closed without merging**
