### PR TITLE
fix: Merging the .gitignore with one present in root

### PR DESCRIPTION
**Pull request by vishakhanihore**
- There are two .gitignore in our repository. Merging them into one

### CODE REVIEW

**Comment by mrbobbytables** [comment]
My thought behind putting it in the content directory was to act as a signal that there is some things within there that should be ignored. I'm fine with bumping it back up to the root `.gitignore` though.

**Comment by vishakhanihore** [comment]
> My thought behind putting it in the content directory was to act as a signal that there is some things within there that should be ignored. I'm fine with bumping it back up to the root `.gitignore` though.

I think a single `.gitignore` with an explanation in comment should do the work. But if having two would ease the flow, I have no issues in closing.
What do you suggest ?

**Comment by mrbobbytables** [comment]
¯\\_(ツ)_/¯
/approve

**Pull request merged**
