### PR TITLE
feat: Making events page into a scheduler and merging with calendar

### PR DESCRIPTION
**Pull request by vishakhanihore**
- Making the events index page reliable and contented.
- Enhancing the Calendar.
- Merging the Calendar page with Events/Index.
- Events Section is agnostic and complete.

Screenshot 2020-01-13 at 12 33 36 AM

### CODE REVIEW

**Comment by vishakhanihore** [comment]
@parispittman @mrbobbytables There are some issue currently:
- With this PR, Calendar section has been merged with Events/Index and this makes Events section complete.
- There are some bugs which I will solve in later iteration once this design has been accepted.
- I changes the list to grid view as we are using it to display the calendar for community, Grid view fits a lot better on Index Page.
- @mrbobbytables There is an error in JSON Parsin but I checked the network tab, Google API is returning the correct JSON Format but the calendar is unable to parse ?
Please provide inputs.

**Comment by mrbobbytables** [comment]
Thanks!
/lgtm
/approve

**Comment by vishakhanihore** [comment]
@mrbobbytables Yup I thought so, no worries I will send the patch . But
meanwhile, can you check why there is json parsing error?

**Pull request merged**
